pipeline {
    agent any

    environment {
        cluster = "javaprod"
        service = "javaappprodsvc"
    }

    stages {          

        
        stage("Deploy to ECS producation"){
            steps{
                withAWS(credentials: 'awscreds', region: 'us-east-1'){
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service}  --force-new-deployment'
                }
            }
        }
    }

    post {
        success {
            echo "Docker image pushed to ECR successfully!"
        }
        failure {
            echo "Build or push failed!"
        }
    }
}
